### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rcrdlbl** [urcades/rpgchat#1]
link in bio (to `ts.net`) is down

re: monetization strategy –– it would be interesting to make RPGChat a ["Raw Game"](https://fandomwire.com/hideo-kojimas-canceled-game-could-have-changed/)

**Comment by urcades** [comment]
@rcrdlbl ty for the issue, game demo is up again:

https://oleaceae.saga-owl.ts.net/

Also, amazing reference, adding it to the stack...
